stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:20-alpine
  script:
    - npm install
    - echo "Test aşaması - şimdilik sadece echo komutu"
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/berkebeyazbenli/myapp:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/berkebeyazbenli/myapp:$CI_COMMIT_SHA
  only:
    - main
  dependencies:
    - build 