stages:
  - build
  - test

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - echo "Build completed successfully!"
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:20-alpine
  script:
    - npm install
    - echo "Test aşaması - şimdilik sadece echo komutu"
    - echo "All tests passed!"
  dependencies:
    - build 