apiVersion: v1
kind: ServiceAccount
metadata:
  name: express-api-sa
  namespace: express-api-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: express-api-role
  namespace: express-api-namespace
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: express-api-rolebinding
  namespace: express-api-namespace
subjects:
- kind: ServiceAccount
  name: express-api-sa
  namespace: express-api-namespace
roleRef:
  kind: Role
  name: express-api-role
  apiGroup: rbac.authorization.k8s.io 